---
env:
  node: true
plugins:
  - "sort-class-members"
extends: "eslint:recommended"
globals:
  BigInt: true
  window: true
parserOptions:
  ecmaVersion: 2020
rules:
  array-bracket-spacing:
    - 2
    - never
  arrow-parens: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: false
  comma-dangle:
    - 2
    - never
  curly: 2
  eol-last:
    - 2
    - always
  indent:
    - 2
    - 2
    - SwitchCase: 1
      ignoreComments: false
  keyword-spacing:
    - 2
    - after: true
      overrides:
        catch:
          after: true
        for:
          after: true
        if:
          after: true
        switch:
          after: true
        while:
          after: true
  no-prototype-builtins: 0
  no-trailing-spaces: 2
  no-var: 2
  object-curly-spacing:
    - 2
    - always
  object-shorthand:
    - 2
    - consistent-as-needed
  prefer-const: 2
  quotes:
    - 2
    - single
  require-atomic-updates: 1
  semi:
    - 2
    - always
  sort-class-members/sort-class-members:
    - 2
    - order:
      - constructor
      - update
      - "[alphabetical-getters]"
      - "[alphabetical-conventional-private-methods]"
      - "[alphabetical-methods]"
      - "[everything-else]"
      - "[custom-inspect-method]"
      groups:
        alphabetical-getters:
        - kind: get
          sort: alphabetical
        alphabetical-methods:
        - type: method
          sort: alphabetical
        alphabetical-conventional-private-methods:
        - name: "/_.+/"
          type: method
          sort: alphabetical